spring.datasource.url=jdbc:mysql://localhost:3306/bus_ticket_db
spring.datasource.username=root
spring.datasource.password=Tien9a2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# --- CẤU HÌNH GỬI EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Điền chính xác email mà bạn vừa dùng để lấy mã
spring.mail.username=flechazo26122005@gmail.com

# Dán 16 chữ cái viết liền không dấu cách vào đây
spring.mail.password=ibfyqhjtdnbaxoii

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ==========================================
# CẤU HÌNH CỔNG THANH TOÁN VNPAY (SANDBOX)
# ==========================================
vnpay.tmnCode=KKC3GL2Q
vnpay.hashSecret=40IL1Q9K3UGSIE9Q1KHYMNMC4LLYT53R

# 3. Đường dẫn của VNPAY để chuyển hướng khách hàng sang quẹt thẻ
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# 4. Đường dẫn VNPAY sẽ đá khách hàng về sau khi thanh toán xong
vnpay.returnUrl=http://localhost:8080/api/payments/vnpay-return