spring.datasource.url=jdbc:mysql://localhost:3306/bus_ticket_db
spring.datasource.username=root
spring.datasource.password=Tien9a2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# --- CẤU HÌNH GỬI EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Điền chính xác email mà bạn vừa dùng để lấy mã
spring.mail.username=flechazo26122005@gmail.com

# Dán 16 chữ cái viết liền không dấu cách vào đây
spring.mail.password=ibfyqhjtdnbaxoii

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true